services:
  - type: web
    name: chess-ia
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt ; apt-get update ; apt-get install -y stockfish
    startCommand: python server.py
    autoDeploy: true
